name: UAuth-frontend
main: UAF\UAF
version: 1.0.0
api: 1.13.0
load: STARTUP
author: [PocketMine Team, cr0sh]
authors: [shoghicp, cr0sh]
description: Fork of SimpleAuth, using UAuth API for skin metadata authentication
website: https://tinyw.in/uauth
depend: UAuth
commands:
 login:
  description: "비밀번호를 이용해 로그인합니다."
  usage: "/login <password>"
  permission: uaf.command.login
 register:
  description: "Registers an account"
  usage: "/register <password>"
  permission: uaf.command.register

permissions:
 uaf:
  default: op
  description: "UAF의 모든 권한 허용"
  children:
   uaf.chat:
    description: "로그인되어 있지 않아도 채팅 허용"
    default: false
   uaf.move:
    description: "로그인되어 있지 않아도 움직일 수 있음"
    default: false
   uaf.lastid:
    description: "설정에서 최근 ID로 로그인하는 기능이 활성화되어 있으면 사용"
    default: true
   uaf.command:
    description: "UAF 명령어 사용"
    default: true
    children:
     uaf.command.register:
      description: "UAF 비밀번호 생성"
      default: true
     uaf.command.login:
      description: "UAF 로그인"
      default: true
